### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by hayashi164** [hayashi164/collect-paper#13]
実装予定のissueのToDoをまとめる

**Comment by hayashi164** [comment]
# 実装
- [ ] https://github.com/hayashi164/collect-paper/issues/14
- [ ] https://github.com/hayashi164/collect-paper/issues/15
- [ ] https://github.com/hayashi164/collect-paper/issues/16
- [ ] https://github.com/hayashi164/collect-paper/issues/17

# Azure移管

# GithubAcitions
 - [ ] https://github.com/hayashi164/collect-paper/issues/4

# Github関連
 - [ ] https://github.com/hayashi164/collect-paper/issues/6
 - [ ] https://github.com/hayashi164/collect-paper/issues/11 

# 環境
 - [ ] https://github.com/hayashi164/collect-paper/issues/3
